// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database.sql

package database

import (
	"context"
)

const resetDatabase = `-- name: ResetDatabase :exec
TRUNCATE TABLE users
`

func (q *Queries) ResetDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDatabase)
	return err
}
